apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-demo
spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: reactjs-demo

  template:
    metadata:
      labels:
        app: reactjs-demo

    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: reactjs-demo
        image: gcr.io/digidhamu-k8s/reactjs-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi          

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-demo
spec:
  type: NodePort
  ports:
  - name: reactjs-demo
    port: 8008
    targetPort: 80
    nodePort: 32008
  selector:
    app: reactjs-demo

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: demo-daas-digidhamu-com
  annotations:
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # tls:
  # - secretName: daas-digidhamu-com-tls
  #   hosts:
  #   - daas.digidhamu.com

  rules:
  - host: daas.digidhamu.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: reactjs-demo
            port:
              number: 8008
